import { YT, YTNodes } from 'youtubei.js';
import { getInnertube } from '.';
import type {
	ChannelContent,
	ChannelContentPlaylists,
	ChannelContentTypes,
	ChannelContentVideos,
	ChannelOptions,
	ChannelPage,
	Image,
	PlaylistPage,
	Video
} from '../model';
import { invidiousItemSchema } from './schema';
import { associateAvatar } from '$lib/thumbnail';

export async function getChannelYTjs(channelId: string): Promise<ChannelPage> {
	const innertube = await getInnertube();

	const innerResults = await innertube.getChannel(channelId);

	let authorBanners: Image[] = [];
	if (
		innerResults.header?.is(YTNodes.PageHeader) &&
		innerResults.header.content?.is(YTNodes.PageHeaderView)
	) {
		authorBanners = innerResults.header.content.banner?.image ?? [];
	}

	if (innerResults.metadata.avatar) await associateAvatar(channelId, innerResults.metadata.avatar);

	const description = innerResults.metadata.description ?? '';

	return {
		type: 'channel',
		allowedRegions: innerResults.metadata.available_countries ?? [],
		tabs: innerResults.tabs.map((tab) => tab.toLowerCase().replace('live', 'streams')),
		latestVideos: [],
		isFamilyFriendly: true,
		author: innerResults.metadata.title ?? '',
		authorThumbnails: innerResults.metadata.avatar ?? [],
		authorId: channelId,
		authorBanners,
		joined: 0,
		authorVerified: true,
		totalViews: 0,
		authorUrl: `/channel/${channelId}`,
		subCount: 0,
		autoGenerated: false,
		description,
		descriptionHml: description
	};
}

/**
 * Most channel tabs are a rich grid of rich items. Playlists are not: they come
 * back as a plain grid nested in a section list, and their cards sit directly in
 * that grid rather than being wrapped.
 */
function channelTabContents(innerResults: YT.Channel | YT.ChannelListContinuation) {
	if (innerResults instanceof YT.Channel) {
		const content = innerResults.current_tab?.content;

		if (content?.is(YTNodes.RichGrid)) return content.contents;

		if (content?.is(YTNodes.SectionList)) {
			return content.contents.firstOfType(YTNodes.ItemSection)?.contents.firstOfType(YTNodes.Grid)
				?.contents;
		}

		return undefined;
	}

	if (innerResults.contents?.is(YTNodes.AppendContinuationItemsAction)) {
		return innerResults.contents.contents;
	}

	return undefined;
}

export function invidiousChannelContentSchema(
	innerResults: YT.Channel | YT.ChannelListContinuation,
	author: string,
	authorId: string
) {
	const videos: Video[] = [];

	const contents = channelTabContents(innerResults);
	if (!contents) return videos;

	contents.forEach((item) => {
		const node = item.is(YTNodes.RichItem) ? item.content : item;
		if (!node) return;

		const invidiousSchema = invidiousItemSchema(node);

		// Shorts parse into their own item type, so keeping only 'video' here
		// discarded every one of them and left the shorts tab always empty.
		if (invidiousSchema?.type === 'video' || invidiousSchema?.type === 'shortVideo') {
			invidiousSchema.author = author;
			invidiousSchema.authorId = authorId;
			videos.push(invidiousSchema);
		}
	});

	return videos;
}

function invidiousChannelPlaylistsSchema(
	innerResults: YT.Channel | YT.ChannelListContinuation,
	author: string,
	authorId: string
): PlaylistPage[] {
	const playlists: PlaylistPage[] = [];

	const contents = channelTabContents(innerResults);
	if (!contents) return playlists;

	contents.forEach((item) => {
		const node = item.is(YTNodes.RichItem) ? item.content : item;
		if (!node) return;

		const invidiousSchema = invidiousItemSchema(node);
		if (invidiousSchema?.type !== 'playlist') return;

		// The card carries what a listing needs; the rest is filled in when the
		// playlist itself is opened.
		playlists.push({
			...invidiousSchema,
			author: invidiousSchema.author || author,
			authorId: invidiousSchema.authorId || authorId,
			description: '',
			descriptionHtml: '',
			viewCount: 0,
			updated: 0,
			isListed: true,
			videos: []
		});
	});

	return playlists;
}

function fetchChannelContentVideosWithContinuation(
	innerResults: YT.ChannelListContinuation,
	author: string,
	authorId: string
): () => Promise<ChannelContentVideos> {
	return async () => {
		const continuation = await innerResults.getContinuation();
		return {
			videos: invidiousChannelContentSchema(continuation, author, authorId),
			getContinuation: fetchChannelContentVideosWithContinuation(continuation, author, authorId)
		};
	};
}

function fetchChannelPlaylistsWithContinuation(
	innerResults: YT.ChannelListContinuation,
	author: string,
	authorId: string
): () => Promise<ChannelContentPlaylists> {
	return async () => {
		const continuation = await innerResults.getContinuation();
		return {
			playlists: invidiousChannelPlaylistsSchema(continuation, author, authorId),
			getContinuation: fetchChannelPlaylistsWithContinuation(continuation, author, authorId)
		};
	};
}

async function fetchChannelContentWithContinuation(
	innerResults: YT.Channel | YT.ChannelListContinuation,
	author: string,
	authorId: string,
	type: ChannelContentTypes
): Promise<ChannelContent> {
	const continuation = innerResults.has_continuation ? 'logicalPlaceholder' : undefined;

	// The playlists tab has to be returned in its own shape, or the page has
	// nothing to render: it reads playlists, never videos.
	if (type === 'playlists') {
		const playlistContent: ChannelContentPlaylists = {
			continuation,
			playlists: invidiousChannelPlaylistsSchema(innerResults, author, authorId)
		};

		if (continuation) {
			playlistContent.getContinuation = fetchChannelPlaylistsWithContinuation(
				innerResults as YT.ChannelListContinuation,
				author,
				authorId
			);
		}

		return playlistContent;
	}

	const channelContent: ChannelContent = {
		continuation,
		videos: invidiousChannelContentSchema(innerResults, author, authorId)
	};

	if (channelContent.continuation) {
		channelContent.getContinuation = fetchChannelContentVideosWithContinuation(
			innerResults as YT.ChannelListContinuation,
			author,
			authorId
		);
	}

	return channelContent;
}

export async function getChannelContentYTjs(
	channelId: string,
	options: ChannelOptions
): Promise<ChannelContent> {
	const innertube = await getInnertube();

	const channel = await innertube.getChannel(channelId);

	const author = channel.metadata.title ?? '';

	let innerResults: YT.Channel | YT.ChannelListContinuation;
	if (options.type === 'videos') {
		innerResults = await channel.getVideos();
	} else if (options.type === 'playlists') {
		innerResults = await channel.getPlaylists();
	} else if (options.type === 'shorts') {
		innerResults = await channel.getShorts();
	} else {
		innerResults = await channel.getLiveStreams();
	}

	if (options.sortBy && innerResults instanceof YT.Channel) {
		try {
			innerResults = await innerResults.applySort(options.sortBy);
		} catch {
			// sort filter not available for this tab
		}
	}

	return fetchChannelContentWithContinuation(
		innerResults,
		author,
		channelId,
		options.type ?? 'videos'
	);
}
